### ISSUE TITLE
HTML preview metadata entry

### ISSUE THREAD

**Issue by simleo** [ResearchObject/ro-crate#106]
The spec describes how `ro-crate-preview.html`, if present, should be structured, but does not specify if and how to refer to it in the metadata file. The Workflow RO-Crate spec shows the following example:

```json
{
      "@id": "ro-crate-preview.html",
      "@type": "CreativeWork",
      "about": {"@id": "./"}
}
```

Which seems to be followed by WorkflowHub. Should the RO-Crate spec recommend this explicitly? What about `ro-crate-preview-files/`?

**Comment by ptsefton** [comment]
I think preview files should be left out of the JSON-LD. If we do have a convention for listing the HTML file then it will need to have an appropriate conformsTo property  - to distinguish it form the Ro-crate-metadata Descriptor.

**Comment by stain** [comment]
I don't think the `ro-crate-preview.html` should have a `conformsTo` as we have in 1.1 reduced the requirement of what the preview HTML file has to list.

Perhaps as @simleo suggest it would make sense for it to be (able to be) listed - specially if it may have been written by a person who should get credit. It would also mean that within the HTML file itself, which embers a copy of the JSON-LD, it would self-declare what it's about.

**Comment by stain** [comment]
Suggest moving this for after 1.1

**Comment by simleo** [comment]
> Perhaps as @simleo suggest it would make sense for it to be (able to be) listed

If so, should it be typed as `["File", "CreativeWork"]` and referenced from the root dataset via `"hasPart"`?

**Comment by stain** [comment]
I think `ro-crate-preview.html` is not what we call a [Data entity](https://www.researchobject.org/ro-crate/1.1/data-entities.html), and should not be considered part/contained of the RO-Crate. Rather it "is" the RO-Crate, just like `ro-crate-metadata.json` - they are siblings that represent or serialize the conceptualization of this particular crate.

It is often hard to distinguish between data and metadata, but I think at least at this level we have to agree these two files are metadata about all the other things!

If we listed `ro-crate-preview.html`, then it is kind of saying "OK, reader of `ro-crate-metadata.json`, you will find more info in this HTML file" and vice versa. But the two files would typically contain more or less the same information.

If the preview file also took the role of a README/index file that also described the Crate further (and that info was not in the JSON-LD), then perhaps `hasPart` and "upgrading" to `File` would be appropriate. But what I've seen is that this has tended to be a separate file, if included, which perhaps also explains that it is an RO-Crate.

**Comment by stain** [comment]
another reason for leaving it out is that it may become wrong on editing.. as a "magical" filename declared in spec, an editor is free to just delete it or replace it. But if it's declared as an entity then perhaps it needs to be preserved.. unless as you say we make it "conformsTo" tagged or similar? 

It should be fine to "augment" a RO-Crate with no preview file and add it in, without having to update the JSON-LD in both cases. This could otherwise lead to inconsistencies. It's not a problem the other way because `ro-crate-metadata.json` is mandatory. 

However I can see a reason why - in the `ro-crate-preview.html` itself, we will also have the JSON-LD included -- but within there is no link from the HTML document you are in, to what it's about, and that is what the fragment with `about` would add, and which search engines would also wonder about. In a sense there it would help make `./` a top node like in the JSON-LD equivalent.

So do we simply recommend that such a statement is added in the Preview's embedded JSON-LD?

**Comment by stain** [comment]
I think we need to settle on this and recommend one way or the other explicitly in the spec.

**Comment by stain** [comment]
Could be alternative `conformsTo` that indicates the preview section. But this file may be re-generated and not fixed/expected to exist.

**Comment by stain** [comment]
@marc-portier says we can permit it, but it is optional. It should then be listed as a derived entity from the metadata JSON. Can include when was it made, and by which tool.
