### ISSUE TITLE
Tools link is broken

### ISSUE THREAD

**Issue by longr** [ResearchObject/ro-crate#143]
**Describe the bug**
The "tools" link in https://www.researchobject.org/ro-crate/#how-can-i-use-it is broken.  It tried to access the md file instead of the rendered html.

**URL**
https://www.researchobject.org/ro-crate/tools.md

**Suggested fix**
I cannot see why this does not render correctly, so I cannot provide a fix I am afraid.

**Additional context**
N/A

**Comment by bedroesb** [comment]
Good catch! Last contentathon we decided to have separate pages for tools and usecases, which leads to those pages being in their own directory + index file. If you want to link towards a directory, we should not add .md as link, because the html equivalent does not exist. The correct linking should be [tools](tools/) like it is done with [RO-Crate specification 1.1](1.1/). If #142 is merged, this should be fixed.

**Comment by bedroesb** [comment]
@longr This is fixed.
