### ISSUE TITLE
Use Case: Allow RO-Crates to have root dataset IDs other than "./"

### ISSUE THREAD

**Issue by ptsefton** [ResearchObject/ro-crate#183]
As a **profile designer**, I want **to allow RO-Crates to have IDs that are not `./`** so that ** ro-crate-metadata can be served over an API**. 

"./" was originally a magic name until Stian came up with the metadata descriptor - the convention is no longer needed and is meanigless if the ro-crate metadata is not in a file on disk but is served via an API.

- See also  #178

**Comment by simleo** [comment]
The spec already allows this (since version 1.1): the root data entity [SHOULD have an `@id` of `./`](https://www.researchobject.org/ro-crate/1.1/root-data-entity.html#ro-crate-metadata-file-descriptor). This is [not handled by ro-crate-py yet](https://github.com/ResearchObject/ro-crate-py/issues/34) though. Perhaps we want to get rid of this recommendation and write something like "legacy specs (until version 1.0) required the root data entity to have an `@id` of `./`; this is still recommended for RO-Crates stored as file system directories" instead.

**Comment by stain** [comment]
@simleo however  [properties of the root data entity](https://www.researchobject.org/ro-crate/1.1/root-data-entity.html#direct-properties-of-the-root-data-entity) includes:

>@id: MUST end with `/` and SHOULD be the string `./`

I think we can soften that `MUST` to another `SHOULD` - athough then the _Root Data Entity_ is more of risk of not having anything to do with the [_root directory_](https://www.researchobject.org/ro-crate/1.1/structure.html)  which could get confusing. 

So do we need to clarify the terminology then? This entity then becomes the "RO-Crate" rather than of the RO-Crate Root (which is effectively how it is used). Note that the current _root_ terminology helped to avoid "The RO-Crate is made of the RO-Crate" loops

**Comment by simleo** [comment]
Discussed this morning at the meeting. One of the main issues raised was that if the root data entity id is an arbitrary URI, then it's not clear what to do with relative paths of data entities. @dgarijo came up with an idea that many of us found great, myself included: state that relative paths are unsupported in data entities (behavior of implementation is undefined) if the root data entity id is not `./`. In other words, the root data entity id may be an arbitrary URI, but then all data entities must have an absolute URI as their id.

**Comment by dgarijo** [comment]
@simleo thanks for the credit, but I think it was @stain and @ptsefton who proposed it. I just rephrased emphasizing the 2 use cases focus on  (i.e., leave out of scope relative paths if the root data entity id is not `./`)

**Comment by stain** [comment]
As suggested in #189 when trying to add this I had trouble with repeated references to _RO-Crate Root Directory_ which becomes tricky if the root dataset no longer is grounded in a directory (with `ro-crate-metadata.json` may or may not be implied to be in such a directory)

**Comment by stain** [comment]
Check minutes as we think it was decided `@id` can be URI? 

@simleo Spec already allows URI, (but requires `/` at end). Touches on detached/attached crate and nesting of crates.

We agreed that implementation can try to be lax and rescue user -- but spec should be more strict. Don't suggest the heuristics. Just note to not expose internals of nested crates as it could confuse root dataset algorithm.
