### ISSUE TITLE
Question: Why does the crate need to be flattened?

### ISSUE THREAD

**Issue by marcolarosa** [ResearchObject/ro-crate#47]
Hi,

I've been using RO-Crate to define objects in an OCFL filesystem and I've been wondering why the crates need to be flattened.

From my limited experience of working with ro-crates and json-ld I see that flattening is something that the user could do if they wanted to work with a crate in that form. Perhaps I'm wrong but in my experience the system that creates a crate (e.g. my code) first builds something like:

```
{
  "@context": "https://raw.githubusercontent.com/ResearchObject/ro-crate/master/docs/0.2-DRAFT/context.json",
  "@graph": [
    {
      "@id": "./",
      "@type": [
        "Dataset",
        "RepositoryObject"
      ],
      "author": {
        "name": "A Person",
        "givenName": "A",
        "lastName": "Person"
      },

---- snip ----
```

As a human I can easily parse this information and understand it. Furthermore, as a developer that is going to ingest this data into elastic search - a document oriented search service - I can just pass it as is and get on with the job.

By comparison - the flattened crate:
```
{
  "@context": "https://raw.githubusercontent.com/ResearchObject/ro-crate/master/docs/0.2-DRAFT/context.json",
  "@graph": [
    {
      "@id": "./",
      "@type": [
        "Dataset",
        "RepositoryObject"
      ],
      "additionalType": "item",
      "author": {
        "@id": "_:b0"
      },
---- snip ----
  },
    {
      "@id": "_:b0",
      "givenName": "A",
      "name": "A Person
    },
}
```

imposes a greater mental load (I need to follow the id links to see what author resolves to) to parse the information and also means that I have to reconstruct the object in order to use it with elastic.

So - if it's easy for anyone using a crate to flatten and compact the object (which it is), and given that the crate is likely to be used by code which can flatten and compact it at will, why does the spec require this to happen up-front? 

It seems to me that not enforcing the flattening results in a best of both worlds system. A human reading a crate would see a fairly easy to read JSON object whilst a consumer (code) could flatten the crate as it desires.

**Comment by ptsefton** [comment]
We have put flattening in so that crates for distribution have a predicable graph structure.

It would indeed have been nice if we could have a hierarchical structure like the one you show as a default where authors are neatly nested off the crate but there a several issues with this.

1.   If you use JSON-LD tools to transform the crate metadata then it's hard to get it back into the form you show - framing might help with this but it's too hard.

2.  If you have a lot of authors, which are people that are linked to on several Datasets and Files etc then you end up still having to resolve links, or end up with a lot of redundant JSON and potential for error - the same author would need to be repeated in several spots (I'm not even sure how this would work in JSON-LD but it would be messy).

3. Human readability of the JSON is not a design goal - that's why there's an HTML file option that IS designed to make stuff human readable.

4. Programmer friendliness _is_ a design goal and in our judgement flattened JSON is easy to work with - it is simple to iterate over the flattened graph, build an index by ID and then have straightforward lookup functions. This means that naive programmers can write RO-Crate consuming tools without having to have access to JSON-LD library to normalised (by which I mean flatten) docs, meaning you can work in any language with a JSON library without needing a JSON-LD library.

**Comment by marcolarosa** [comment]
*I'll start by saying that I don't need the spec to change in any way as I'm happy to work with it as is and can do so as I point out further on.*

I can't argue with the point about having a predictable graph structure; indeed that makes a lot of sense to me and means the data is deduplicated which is always nice.

1. I might be misunderstanding you but that's why I'm asking if flattening is necessary up front. 

A producer of an ro-crate could provide a structure that makes sense for them and their use cases / data and consumers could flatten that structure using standard tools, verify that it's a valid crate in flattened form and then continue on to use it if it is (though this goes against your point 4. which makes perfect sense and also shifts the burden of verification to the consumer...). 

From what I can see the JSON-LD tools enable you to go from object to flattened but not the other way around so storing the crate as an object rather than a flattened graph doesn't take anything away.

A consumer could choose to use whichever form was most convenient for them (subject to caveats on point 4.)

3. Fair enough. 

2. I think this is the point i'm having the most trouble grasping so I'll put down some thoughts that will hopefully clarify what i'm struggling with.

The example above is trivial so let's say that I create an ro-crate like:

```
{
  --- snip ---
  author: {A},
  contributors: [{A}, {B}, ..., {n}],
  papers: [{
    contributors: [{A}, {B}, ..., {n}],
    citations: [{
        authors: [{A}, {B},...{n}]
    }]
  },
  ...]
  --- snip ---
```

Contrived example but the point is there is lots of redundant data and potentially arbitrary nesting.

This crate or the simpler one above would be created from a templating engine. Assuming it's a valid JSON-LD file (which I'm not sure about) the problem is not the potential for error but rather, the redundancy in the data. Ultimately, the object can be recreated by walking the links as one would a filesystem (which is in fact what I do : https://github.com/CoEDL/modpdsc/blob/master/ocfl-indexer/jsonld-loader.js#L70-L139).

So this doesn't negate the sensible idea of having a predictable graph structure or the deduplication of the data. It's just an extra step for me to go backwards from a crate.

The alternative in my mind would be to store the raw object and call on ro-crate tools to verify the crate before I use it (where the tool would flatten and then verify that crate is valid).

**Comment by stain** [comment]
We agreed in call 2019-10-03 that:

* Stian has come to same conclusion as Peter
* Finding all elements of same type very easy (e.g. all Persons, instruments etc.)
* Similar approach taken by prov.py https://prov.readthedocs.io/ 
* Interop with Datacite Bolognese and Google Data Search
* We may need a re-framed version for tree consumption 
* Not for now, but to keep in mind
* Peter: ro-crate.js library can add flattening
* Carole - pivoting & being able to navigate around the document is something helped by flattening
* @eocarragain  to reply and close issue
* Agree: ultimately this should go in a FAQ/website.

**Comment by stain** [comment]
I also added in #50 that [describing in flat list](https://github.com/ResearchObject/ro-crate/blob/intro-jsonld/docs/0.3-DRAFT/index.md#describing-entities-in-json-ld) may need new identifiers. I suggest local `#` identifiers rather than `_:` blank node identifers as the tree approach would have added if `@id` is missing.

**Comment by marcolarosa** [comment]
Ok. I'll close this issue but most of the feedback doesn't disagree with what I was asking about. 

Flattening is easy. Going the other way is not. I need it the other way in a real use case. http://45.113.232.73/ works off ro-crates stored in OCFL. In order to use the crate; i need to unflatten it. The burden is on me to write that code. 

If it were as I asked, the burden of writing and maintaining the flattening code would reside with the json-ld library that I'm using. I'm sure other libraries provide the same functionality.

**Comment by alaninmcr** [comment]
The flattening for RO-Crate makes a mismatch between the markup that is needed for RO-Crate and that already used by some (many?) schema.org conformant sites. This causes an additional hurdle for the adoption of RO-Crate.

**Comment by stain** [comment]
I don't think we want to allow any arbitrary JSON-LD forms as then you are forced to process RO-Crate using JSON-LD tooling. Too many dimensions of flexibility in creating the JSON-LD means it is harder to consume or edit.

However it is right that existing schema.org examples, Bioschemas examples and usage elsewhere is frequently using nested JSON-LD objects, which can be confusing when trying to repurpose these in RO-Crate. We should make that clearer, and also reiterate the arguments expressed here and in #9.

In "regular schema.org" world that is not a big problem because you have each JSON-LD markup on a separate HTML pages, and so you only ever describe one main entity. But in RO-Crate we naturally want to describe all the things in the crate (to a varying degree of detail).

Perhaps we should make a FAQ indicating the RO-Crate approach and gather the links to the different points of specification on this:

# About flattening in RO-Crate spec

https://www.researchobject.org/ro-crate/1.1/structure.html#ro-crate-metadata-file-ro-crate-metadatajson
> The RO-Crate Metadata File MUST contain RO-Crate JSON-LD; a valid JSON-LD 1.0 document in flattened and compacted form
> ...
> The appendix RO-Crate JSON-LD details the general structure of the JSON-LD that is expected in the RO-Crate Metadata File. In short, the rest of this specification describe the different types of entities that can be added as {} objects to the RO-Crate JSON-LD @graph array below:

```
{ "@context": "https://w3id.org/ro/crate/1.1/context",
  "@graph": [

  ]
}
```

https://www.researchobject.org/ro-crate/1.1/metadata.html#differences-from-schemaorg
> ## Differences from Schema.org 
> ...
> **WARNING**: JSON-LD examples given on the [Schema.org website] may not be in flattened form; any nested entities in RO-Crate JSON-LD SHOULD be described as separate contextual entities in the flat @graph list.


https://www.researchobject.org/ro-crate/1.1/appendix/jsonld.html#describing-entities-in-json-ld

> ## Describing entities in JSON-LD 
> The example below shows the overall structure of a flattened, compacted RO-Crate Metadata File where @context refers to the RO-Crate JSON-LD Context, while @graph is a flat array of the entities that constitute this RO-Crate.
> ...
> The order of the @graph array is not significant. Above we see that the RO-Crate JSON-LD graph contains the RO-Crate Metadata File Descriptor, the Root Data Entity, any Data Entities and any Contextual Entities.
> ..
> Because the RO-Crate JSON-LD is flattened, all described entities must be JSON objects as direct children of the @graph element rather than being nested under another object or array. Properties referencing entities must use a JSON object with @id as the only key, e.g. "author": {"@id": "https://orcid.org/0000-0002-1825-0097"}
> If no obvious identifier is available for a contextual entity, an identifier local to the RO-Crate Metadata File can be generated, for instance {"@id": "#alice"} or {"@id": "#ac0bd781-7d91-4cdf-b2ad-7305921c7650"}. Although it is RECOMMENDED to use #-based local identifiers, identifiers in @id MAY alternatively be a blank node identifier (e.g. _:alice).

https://www.researchobject.org/ro-crate/1.1/appendix/implementation-notes.html#programming-with-json-ld

> ## Programming with JSON-LD
>     RO-Crate JSON-lD has a flat structure; every entity is a JSON object directly within the @graph array in the RO-Crate Metadata File. A useful strategy when processing a crate is to build a look-up table and/or function so that entities can be found via their ID, for example provide a method such as getEntity(id) which returns an entity by its id or a null value if it’s not there.

https://www.researchobject.org/ro-crate/1.1/appendix/relative-uris.html#flattening-json-ld-from-nested-json

>  ## Flattening JSON-LD from nested JSON
> If performing JSON-LD flattening to generate a valid RO-Crate Metadata File, add @base: null to the input JSON-LD @context array to avoid expanding relative URI references. The flattening @context SHOULD NOT need @base: null.
> Example, this JSON-LD is in compacted form which may be beneficial for processing, but is not yet valid RO-Crate Metadata File as it has not been flattened into a @graph array.
> ...

https://www.researchobject.org/ro-crate/1.1/appendix/jsonld.html#ro-crate-json-ld-context

> ## RO-Crate JSON-LD Context
> ...
> RO-Crate consumers SHOULD NOT do the opposite substitution from an embedded context, but MAY use the JSON-LD flattening algorithm with compaction to a referenced RO-Crate JSON-LD context (see also notes on handling relative URI references below).
> 
> **Tip**:   The JSON-LD flattening & compaction algorithms can be used to rewrite to a different @context, e.g. to https://schema.org/docs/jsonldcontext.jsonld or a different version of the RO-Crate JSON-LD Context.

**Comment by stain** [comment]
For instance, common nested example of a `CreativeWork` with an `creator` that do not use `@id` will introduce blank nodes and duplicate person entities (or at least duplicate information) when that same person appear again on as creator of a second entity.

Let's say someone has found https://schema.org/MusicRecording and want to record an RO-Crate of a lyrics text file and an MP3 recording. Alan and Stian made the lyrics, Stian made the MP3, and Stian made the RO-Crate putting it together. They both work at Univ of Manchester, but Stian is also affiliated with University of Amsterdam. The Manchester uni is the publisher of the Crate.

In JSON-LD flattened form we currently get a flat listing according to the [RO-Crate structure](https://www.researchobject.org/ro-crate/1.1/structure.html#ro-crate-metadata-file-ro-crate-metadatajson):

* The RO-Crate Metadata file descriptor (basically our RO-Crate version)
* The root dataset
* The data entities `lyrics.txt` and `song.mp3`
* Contextual entities
  - Each person identified by ORCID
  - Each organisation identified by ROR

The order does not matter as they are all linked by `@id`, but this can be a useful guide.

```json
{
  "@context": "https://w3id.org/ro/crate/1.1/context",
  "@graph": [
    {
        "@type": "CreativeWork",
        "@id": "ro-crate-metadata.json",
        "conformsTo": {"@id": "https://w3id.org/ro/crate/1.1"},
        "about": {"@id": "./"}
    },
    {
      "@id": "./",
      "@type": "Dataset",
      "author": {
        "@id": "https://orcid.org/0000-0001-9842-9718"
      },
      "description": "A masterpiece by Alan and Stian",
      "hasPart": [
        { "@id": "lyrics.txt"},
        {"@id": "song.mp3"}
      ],
      "name": "The Famous Song",
      "publisher": {"@id": "https://ror.org/03f0f6041"}
    },
    {
      "@id": "lyrics.txt",
      "@type": ["File","MusicComposition"],
      "creator": [
        {"@id": "https://orcid.org/0000-0003-3156-2105"},
        {"@id": "https://orcid.org/0000-0001-9842-9718"}
      ],
      "name": "Lyrics of the The Famous Song"
    },
    {
      "@id": "song.mp3",
      "@type": ["File","MusicRecording"],
      "creator": {"@id": "https://orcid.org/0000-0001-9842-9718"},
      "name": "Recording of the The Famous Song",
      "recordingOf": {"@id": "lyrics.txt"}
    },
    {
      "@id": "https://orcid.org/0000-0001-9842-9718",
      "@type": "Person",
      "affiliation": [
        { "@id": "https://ror.org/027m9bs27"},
        {"@id": "https://ror.org/04dkp9463"}
      ],
      "name": "Stian Soiland-Reyes"
    },
    {
      "@id": "https://orcid.org/0000-0003-3156-2105",
      "@type": "Person",
      "affiliation": { "@id": "https://ror.org/027m9bs27"},
      "name": "Alan R Williams"
    },
    {
      "@id": "https://ror.org/027m9bs27",
      "@type": "Organization",
      "name": "The University of Manchester"
    },
    {
      "@id": "https://ror.org/04dkp9463",
      "@type": "Organization",
      "name": "University of Amsterdam"
    }
  ]
}

```

**Comment by stain** [comment]
Now let's try with the nested form. First I tried https://json-ld.org/playground/ with this JSON-LD frame

```json
{"@context": "https://w3id.org/ro/crate/1.1/context", 
 "@id": "ro-crate-metadata.json"
}
```

This basically makes the Metadata file descriptor the root object, avoiding @graph all together:

```json
{
  "@context": "https://w3id.org/ro/crate/1.1/context",
  "@id": "ro-crate-metadata.json",
  "@type": "CreativeWork",
  "conformsTo": {
    "@id": "https://w3id.org/ro/crate/1.1"
  },
  "about": {
    "@id": "./",
    "@type": "Dataset",
    "author": {
      "@id": "https://orcid.org/0000-0001-9842-9718",
      "@type": "Person",
      "affiliation": [
        {
          "@id": "https://ror.org/027m9bs27",
          "@type": "Organization",
          "name": "The University of Manchester"
        },
        {
          "@id": "https://ror.org/04dkp9463",
          "@type": "Organization",
          "name": "University of Amsterdam"
        }
      ],
      "name": "Stian Soiland-Reyes"
    },
    "description": "A masterpiece by Alan and Stian",
    "hasPart": [
      {
        "@id": "lyrics.txt",
        "@type": [
          "File",
          "MusicComposition"
        ],
        "creator": [
          {
            "@id": "https://orcid.org/0000-0003-3156-2105",
            "@type": "Person",
            "affiliation": {
              "@id": "https://ror.org/027m9bs27"
            },
            "name": "Alan R Williams"
          },
          {
            "@id": "https://orcid.org/0000-0001-9842-9718"
          }
        ],
        "name": "Lyrics of the The Famous Song"
      },
      {
        "@id": "song.mp3",
        "@type": [
          "File",
          "MusicRecording"
        ],
        "creator": {
          "@id": "https://orcid.org/0000-0001-9842-9718"
        },
        "name": "Recording of the The Famous Song",
        "recordingOf": {
          "@id": "lyrics.txt"
        }
      }
    ],
    "name": "The Famous Song",
    "publisher": {
      "@id": "https://ror.org/03f0f6041"
    }
  }
}
```

Well, that's nice! Now I can address `$.about.author.affiliation[1].name` and find "The University of Manchester"! No for-loops?

But hang on, what happened with `lyrics.txt`, why are Alan's affiliations included, but not Stian's affiliations?

```json
        "creator": [
          {
            "@id": "https://orcid.org/0000-0003-3156-2105",
            "@type": "Person",
            "affiliation": {
              "@id": "https://ror.org/027m9bs27"
            },
            "name": "Alan R Williams"
          },
          {
            "@id": "https://orcid.org/0000-0001-9842-9718"
          }
        ],
```

This is because in framing the object is expressed with attributes on its first occurance, but only listed by `@id` reference later. Now suddenly the order **does** matter - if we had listed `song.mp3` first then Alan's affiliation would be detailed there instead.

We see the same with the affiliations, Stian has both organizations detailed as nested objects, but Alan has only a `@id` reference to the previously declared Manchester. 

How can a JSON consumer find the name of Alan's affiliation from above without parsing as JSON-LD into an RDF Graph? 

Well, they have to traverse the depth of the graph from the top again, recursing into any array and object, and hope they find an `@id` somewhere. If they find more than one they will have to do some kind of merging or picking a favourite. Now it would then probably be easier to rather load up a JSON-LD library and query the triples.


The developers generating JSON-LD also now have to make choices about where the different nested objects should be expressed. They may not all agree. For instance the above JSON would also look the same if framing from RDF triples, but they might be making the RO-Crate at JSON-level rather than making RDF triples, in which case we could recommend for  to always express the affiliation organizations wherever they appear. 

From our simple example we can do this by copying from the flattened `@graph` the complete object wherever its `@id` appears. Memory is cheap! This could lead to duplication, but it is OK as long as we have the same `@id` (and the `Organization` does not have other recursing objects):

```json
{
  "@context": "https://w3id.org/ro/crate/1.1/context",
  "@id": "ro-crate-metadata.json",
  "@type": "CreativeWork",
  "conformsTo": {
    "@id": "https://w3id.org/ro/crate/1.1"
  },
  "about": {
    "@id": "./",
    "@type": "Dataset",
    "author": {
      "@id": "https://orcid.org/0000-0001-9842-9718",
      "@type": "Person",
      "affiliation": [
        {
          "@id": "https://ror.org/027m9bs27",
          "@type": "Organization",
          "name": "The University of Manchester"
        },
        {
          "@id": "https://ror.org/04dkp9463",
          "@type": "Organization",
          "name": "University of Amsterdam"
        }
      ],
      "name": "Stian Soiland-Reyes"
    },
    "description": "A masterpiece by Alan and Stian",
    "hasPart": [
      {
        "@id": "lyrics.txt",
        "@type": [
          "File",
          "MusicComposition"
        ],
        "creator": [
          {
            "@id": "https://orcid.org/0000-0003-3156-2105",
            "@type": "Person",
            "affiliation": {
              "@id": "https://ror.org/027m9bs27",
              "@type": "Organization",
              "name": "The University of Manchester"
            },
            "name": "Alan R Williams"
          },
          {
            "@id": "https://orcid.org/0000-0001-9842-9718",
            "@type": "Person",
            "affiliation": [
              {
                "@id": "https://ror.org/027m9bs27",
                "@type": "Organization",
                "name": "The University of Manchester"
              },
              {
                "@id": "https://ror.org/04dkp9463",
                "@type": "Organization",
                "name": "University of Amsterdam"
              }
            ],
            "name": "Stian Soiland-Reyes"
          }
        ],
        "name": "Lyrics of the The Famous Song"
      },
      {
        "@id": "song.mp3",
        "@type": [
          "File",
          "MusicRecording"
        ],
        "creator": {
          "@id": "https://orcid.org/0000-0001-9842-9718",
          "@type": "Person",
          "affiliation": [
            {
              "@id": "https://ror.org/027m9bs27",
              "@type": "Organization",
              "name": "The University of Manchester"
            },
            {
              "@id": "https://ror.org/04dkp9463",
              "@type": "Organization",
              "name": "University of Amsterdam"
            }
          ],
          "name": "Stian Soiland-Reyes"
        },
        "name": "Recording of the The Famous Song",
        "recordingOf": {
          "@id": "lyrics.txt"
        }
      }
    ],
    "name": "The Famous Song",
    "publisher": {
      "@id": "https://ror.org/027m9bs27",
      "@type": "Organization",
      "name": "The University of Manchester"
    }
  }
}
```

Now this is a bit more verbose and error-prone than the flat `@graph` we had before. We would now be free to call one of them "University of Manchester" and another occurance "The University of Manchester", ending up with different `name` values.

I see in this approach a asymmetry, in that you:
* Can generate either with JSON-LD or JSON tooling
* Can only consume with JSON-LD tooling

So ironically storing as a tree structure forces the use of consuming it as a graph; while if we store it as a graph you can consume it as a flat list!

This is not a problem for traditional schema.org markup as that is meant to be produced by the masses, but consumed by the few (e.g. search engines). Here we want consuming and producing to be on equal grounds.

So I see that with allowing non-flattened JSON-LD we would have to add many other constraints to reduce that asymmetry; but that would make it very hard to do round-tripping - if you have to parse as JSON-LD, then you will have to write out as JSON-LD. But then you no longer have fine-control over the JSON any more, and JSON-LD Framing can only do so much.

On the other hand, you can always generate JSON-LD compacted flattened form, the above mega-tree takes in Flattening in http://json-ld.org/playground/ takes us back to the very same `@graph` array we started with - perhaps a couple of elements in a different order.

Now if users were forgetful and didn't put in their `@id` in the nested form, that is no longer true. So that can be a  argument against flattened form - it forces assignment of identifiers. For instance, from:

```json
{
  "@context": "https://w3id.org/ro/crate/1.1/context",
  "@id": "ro-crate-metadata.json",
  "@type": "CreativeWork",
  "conformsTo": {
    "@id": "https://w3id.org/ro/crate/1.1"
  },
  "about": {
    "@id": "./",
    "@type": "Dataset",
    "author": {
      "@type": "Person",
      "affiliation": [
        {
          "@type": "Organization",
          "name": "The University of Manchester"
        },
        {
          "@type": "Organization",
          "name": "University of Amsterdam"
        }
      ],
      "name": "Stian Soiland-Reyes"
    },
    "description": "A masterpiece by Alan and Stian",
    "hasPart": [
      {
        "@id": "lyrics.txt",
        "@type": [
          "File",
          "MusicComposition"
        ],
        "creator": [
          {
            "@type": "Person",
            "affiliation": {
                "@type": "Organization",
                "name": "The University of Manchester"
            },
            "name": "Alan R Williams"
          },
          {
      "@type": "Person",
      "affiliation": [
        {
          "@type": "Organization",
          "name": "The University of Manchester"
        },
        {
          "@type": "Organization",
          "name": "University of Amsterdam"
        }
      ],
      "name": "Stian Soiland-Reyes"
          }
        ],
        "name": "Lyrics of the The Famous Song"
      },
      {
        "@id": "song.mp3",
        "@type": [
          "File",
          "MusicRecording"
        ],
        "creator": {
      "@type": "Person",
      "affiliation": [
        {
          "@type": "Organization",
          "name": "The University of Manchester"
        },
        {
          "@type": "Organization",
          "name": "University of Amsterdam"
        }
      ],
      "name": "Stian Soiland-Reyes"
        },
        "name": "Recording of the The Famous Song",
        "recordingOf": {
          "@id": "lyrics.txt"
        }
      }
    ],
    "name": "The Famous Song",
    "publisher": {
          "@type": "Organization",
          "name": "The University of Manchester"
    }
  }
}
```

we now get a `_:b0` blank node nightmare in framed mode, with many duplication:

```json
{
  "@context": "https://w3id.org/ro/crate/1.1/context",
  "@graph": [
    {
      "@id": "_:b0",
      "@type": "Person",
      "affiliation": [
        {
          "@id": "_:b1"
        },
        {
          "@id": "_:b2"
        }
      ],
      "name": "Stian Soiland-Reyes"
    },
    {
      "@id": "_:b1",
      "@type": "Organization",
      "name": "The University of Manchester"
    },
    {
      "@id": "_:b10",
      "@type": "Organization",
      "name": "University of Amsterdam"
    },
    {
      "@id": "_:b11",
      "@type": "Organization",
      "name": "The University of Manchester"
    },
    {
      "@id": "_:b2",
      "@type": "Organization",
      "name": "University of Amsterdam"
    },
    {
      "@id": "_:b3",
      "@type": "Person",
      "affiliation": {
        "@id": "_:b4"
      },
      "name": "Alan R Williams"
    },
    {
      "@id": "_:b4",
      "@type": "Organization",
      "name": "The University of Manchester"
    },
    {
      "@id": "_:b5",
      "@type": "Person",
      "affiliation": [
        {
          "@id": "_:b6"
        },
        {
          "@id": "_:b7"
        }
      ],
      "name": "Stian Soiland-Reyes"
    },
    {
      "@id": "_:b6",
      "@type": "Organization",
      "name": "The University of Manchester"
    },
    {
      "@id": "_:b7",
      "@type": "Organization",
      "name": "University of Amsterdam"
    },
    {
      "@id": "_:b8",
      "@type": "Person",
      "affiliation": [
        {
          "@id": "_:b9"
        },
        {
          "@id": "_:b10"
        }
      ],
      "name": "Stian Soiland-Reyes"
    },
    {
      "@id": "_:b9",
      "@type": "Organization",
      "name": "The University of Manchester"
    },
    {
      "@id": "./",
      "@type": "Dataset",
      "author": {
        "@id": "_:b0"
      },
      "description": "A masterpiece by Alan and Stian",
      "hasPart": [
        {
          "@id": "lyrics.txt"
        },
        {
          "@id": "song.mp3"
        }
      ],
      "name": "The Famous Song",
      "publisher": {
        "@id": "_:b11"
      }
    },
    {
      "@id": "lyrics.txt",
      "@type": [
        "File",
        "MusicComposition"
      ],
      "creator": [
        {
          "@id": "_:b3"
        },
        {
          "@id": "_:b5"
        }
      ],
      "name": "Lyrics of the The Famous Song"
    },
    {
      "@id": "ro-crate-metadata.json",
      "@type": "CreativeWork",
      "conformsTo": {
        "@id": "https://w3id.org/ro/crate/1.1"
      },
      "about": {
        "@id": "./"
      }
    },
    {
      "@id": "song.mp3",
      "@type": [
        "File",
        "MusicRecording"
      ],
      "creator": {
        "@id": "_:b8"
      },
      "name": "Recording of the The Famous Song",
      "recordingOf": {
        "@id": "lyrics.txt"
      }
    }
  ]
}
```

**Comment by simleo** [comment]
> I don't think we want to allow any arbitrary JSON-LD forms as then you are forced to process RO-Crate using JSON-LD tooling. Too many dimensions of flexibility in creating the JSON-LD means it is harder to consume or edit.

Totally agree. Crates would be _much_ harder to consume or edit -- and also to create, as illustrated in the other comments.

**Comment by ptsefton** [comment]
Closing this as there was a lot of explanation.
