### ISSUE TITLE
Use Case: Avoid @type array for contextual entities

### ISSUE THREAD

**Issue by stain** [ResearchObject/ro-crate#83]
As a **user interface developer**, I want to know a **single type for contextual entities** so that I can choose the most appropriate **UI rendering**.

In https://github.com/UTS-eResearch/describo the interface is broken down by type of contextual entity, e.g. `@type`

however some parts of the RO-Crate text, e.g. https://researchobject.github.io/ro-crate/1.0/#workflows-and-scripts have multiple types in an array:

```jsonld
{  "@id": "workflow.xml",
  "@type": ["File", "SoftwareSourceCode", "Workflow"] }
```

This can make it hard to pick the right type to use for rendering, and there is no guarantee that the order of the list is preserved through JSON-LD processing.

Previously we looked at using http://schema.org/additionalType for extra types - but this is not ideal for schema.org types as it requires full URIs and we really want a more specific type like http://schema.org/ScholarlyArticle to be used where fitting, instead of say http://schema.org/CreativeWork as the subclasses often have additional properties. 

https://researchobject.github.io/ro-crate/1.0/#publications-via-citation-property suggest `ScholarlyArticle` as a contextual entity, but there is no reason why an article could not also be a File part of the RO-Crate, e.g. a preprint PDF. In fact this is in the original http://www.researchobject.org/ vision.

One reason we had before for using `@type` array was that it made it easy to comply with the RO-Crate spec saying one particular type, while also wanting to use a more specific type, or a type from a different vocabulary. Consumers of the RO-Crate would not need to know any class hierarcies or ontologies, as the "base" `@type` would also be listed. 

If we move to a single `@type` then they need at least to have knowledge of the schema.org hierarcy (which we could add to the RO-Crate context - we could still use http://schema.org/additionalType for "external" types when people are extending RO-Crate - however this is not ideal from a Linked Data point where people use properties from the extension but the RDF type would be missing.

We also said before that all entries in a Dataset must be of type `File` - so if they need to also be `SoftwareSourceCode` then you need an array. So this restrictions would also have to be lifted and made into a fallback when no more specific type is available. Similar issue for [ImageObject with EXIF](https://researchobject.github.io/ro-crate/1.0/#extra-metadata-such-as-exif) and [RepositoryObject](https://researchobject.github.io/ro-crate/1.0/#thumbnails) with other types from RO-Crate.

Personally I preferred the old `@type` arrays however the convention above is not described well in the spec. 

I think we need to see what happens if we try to do this change, see for instance pull request #81 that already found issue of `Workflow` vs `Script` vs `File` vs `SoftwareSourceCode` (and decided to simplify for just `SoftwareSourceCode`). I don't think we want everything to just be `File` as again an important http://www.researchobject.org/ principle is to have rich types of the aggregated objects.

Hoping for inputs from @ptsefton and @marcolarosa that raised this issue in the [RO-Crate Community calls](https://s.apache.org/ro-crate-minutes)

**Comment by marcolarosa** [comment]
At the moment (and this is nowhere near final) Describo has a mappings file that maps @type arrays to a singular value in order to determine which type definition to load. 
```
export const mappings = {
    "File, ImageObject": "File",
    "File, SoftwareSourceCode, Workflow": "Workflow",
    "File, ImageObject, WorkflowSketch": "WorkflowSketch",
    "File, Script, SoftwareSourceCode": "Script",
};
```

So for example, an object coming in from a crate with @type = [ 'File', 'ImageObject' ] would be loaded with a File definition. However, at this stage, it's not possible to create a File object within Describo and write it out with an @type = [ 'File', 'ImageObject' ].

We have discussed a way to map from one type to another in a profile (see: https://github.com/UTS-eResearch/describo/issues/70) and this might be part of a solution to this question if @type arrays are to be supported. Specifically, we would have a type definition in Describo (remember, this is what the profile uses to render the UI) called ImageObject that when used writes out an object with @type = [ 'File', 'ImageObject' ].

**Comment by stain** [comment]
It might be needed a button to "promote" something to another type - but the challenge is that the new type may not be a direct subclass of the existing one - e.g.  https://schema.org/ImageObject **is** a subclass of https://schema.org/MediaObject (our `File`), which is subclass of https://schema.org/CreativeWork is not related - but https://schema.org/Article is a sister-class of `MediaObject` so which one would "win"?  

I think the grouping by type like in Describo is very useful, but it needs such a mapping as @marcolarosa (or at least the class hierarchy) describes if is to avoid double-listing. So do I get Marco that you are not that insistent on removing the `@type` arrays anymore?

schema.org offers a derived download of the [class hierarchy](https://schema.org/docs/tree.jsonld) which we could embed/link, although this is simplified, e.g. https://schema.org/VideoGame is only subclass of `Game` and is not listed under its secondary parent `SoftwareApplication`. We could augment it with our new hierarchies like in your mapping.

i would also like as in #71 to use SKOS - it would make it easier to keep both directions of the hierarchy - see https://gist.github.com/stain/39f74513515e34cf9a602c4d6f9cef58#file-schema-skos-flattened-jsonld or the compacted tree https://gist.github.com/stain/39f74513515e34cf9a602c4d6f9cef58#file-schema-skos-framed-jsonld (with duplication for `VideoGame` etc).   -- this could also be done for properties although they don't have a top-level concept equivalent to http://schema.org/Thing.

**Comment by marcolarosa** [comment]
@stain From the perspective of the code a singular type is easier to work with and won't require an application update when someone comes up with another combination. So from that perspective I would argue for a singular main type and a secondary array of subtypes. 

Consider loading into Describo a crate with @type = [ 'File', 'Fruit', 'Apple' ] - Describo wouldn't know what to do with it until that mapping has been provided.

**Comment by fbacall** [comment]
@marcolarosa instead of defining mappings, could you not have a priority listing of types that your application knows about?

i.e. with `File` listed above `ImageObject` so it takes precedence in the case that something has `["File", "ImageObject"]`

**Comment by marcolarosa** [comment]
@fbacall Having a priority list as you mention is definitely doable and TBH, this is something @ptsefton also discussed when we were developing Describo. Though I'd forgotten about it your comment has reminded me that our decision then was to wait on this conversation to occur before we would go back and address it in the tool.

The question for me is how do we determine which is the higher precedence type. We could encode the schema.org hierarchy into Describo but that wouldn't be too different to using a mapping file. It's something that needs to be maintained and doesn't lend itself easily to overrides for specific domains. And this community still needs to decide whether to use least specific or most specific assuming Describo has a type definition for it.

Or, we could just walk the @type array and find a match left to right (more specific) or right to left (least specific) but this assumes the data coming in has a defined order by choice and can be trusted as is.

Furthermore, creating an ImageObject requires Describo to load a `File` definition in order to know what can be described but then write out something with ['File', 'ImageObject'] which would require some toggle to say it should come out that way instead of just @type = ['File'].

I haven't thought this through completely but my feeling is Describo would need to support cascading type definitions to support multiple @types in order to mitigate a massive amount of redundancy. So, a type definition of `ImageObject` would have @type = ['File', 'ImageObject'] but it would inherit all of the properties of the 'File' type definition whilst also adding those specific to `ImageObject`. This is not currently possible.

**Comment by ptsefton** [comment]
A priority list could be pretty simple. File and Dataset are special in RO-Crate - and in an application like Describo they have special user interface elements.

If we move to having a single @type then that is at odds with JSON-LD - and people would still have to code defensively in case someone used multiple types. Using additionalType jsut shifts the same coding issues to a new property - programmers will still have to deal with lists of types  and it breaks RDF interoperability.

So I think the spec shoudl jsut be more explict that certain types of things (like Workflows) are identified using an unordered set of @types (and may have additional extra ones).

**Comment by stain** [comment]
Thanks, @ptsefton, although I notice you don't agree with @marcolarosa in https://github.com/ResearchObject/ro-crate/issues/83#issuecomment-644449024 !

If we agree then to keep `@type` arrays, then we can soften this in other cases, e.g. #81 can use both `@type` <https://schema.org/SoftwareSourceCode> and the not-yet-existing <https://bioschemas.org/Workflow> 

Then we would instead need a paragraph somewhere about `@type` arrays, the defensive coding as you mention. Perhaps showing how this could be used with other vocabularies - right after <https://researchobject.github.io/ro-crate/1.0/#extending-ro-crate> appendix perhaps?

Do you think this mean we should then still keep `File` also on these specialized data entities like `Workflow`? 
Then we should add a section in the main section on how a data entity can be described further, perhaps using <http://schema.org/ScholarlyArticle> as example

**Comment by ptsefton** [comment]
@stian yes I think we should keep File on specialized data entities becuase FIle and Dataset have special status as _Data Entities_ and may get special handling in apps and HTML previews etc -- will draft something for consideration.
